DDD plugin 101 with basic example
buschmais/jqassistant-101 pull request #15
Opened 2019-07-13 14:39 UTC by StephanPirnbaum

2019-09-28 08:50 UTC, DirkMahler requested changes

2019-09-28 08:50 UTC, DirkMahler commented on src/main/tutorials/ddd-plugin/index.adoc
> +The setup above activates the pre-defined group `java-ddd:Default that provides some basic constraints for
` missing after the groupname

2019-09-28 08:50 UTC, DirkMahler commented on src/main/tutorials/ddd-plugin/pom.xml
> +            <version>1.6.0</version>
scope provided

2019-09-28 08:50 UTC, DirkMahler commented on src/main/tutorials/ddd-plugin/pom.xml
> +        </dependency>
scope provided

2019-09-30 06:48 UTC, StephanPirnbaum commented on src/main/tutorials/ddd-plugin/index.adoc
> +The setup above activates the pre-defined group `java-ddd:Default that provides some basic constraints for
Ups, done

2019-09-30 06:48 UTC, StephanPirnbaum commented on src/main/tutorials/ddd-plugin/pom.xml
> +            <version>1.6.0</version>
Done

2019-09-30 06:48 UTC, StephanPirnbaum commented on src/main/tutorials/ddd-plugin/pom.xml
> +        </dependency>
Done

2019-10-01 11:05 UTC, merged