created draft for 2.x migration guide
buschmais/jqassistant-101 pull request #31
Opened 2023-07-30 10:11 UTC by DirkMahler

2023-08-03 06:53 UTC, StephanPirnbaum requested changes

2023-08-03 06:53 UTC, StephanPirnbaum commented on migration-guides/1.x-2.0.adoc
> +* Reduced set of plugins which delivered with the jQAssistant distribution (i.e. Maven plugin and command line utility)
which are

2023-08-03 06:53 UTC, StephanPirnbaum commented on migration-guides/1.x-2.0.adoc
> +NOTE: Existing options can easily be mapped to the new options by their name. The only notable exception is `jqassistant.storeLifeCycle=REACTOR|MODULE` of the Maven plugin which has been renamed and
One or two examples would be good

2023-08-03 06:53 UTC, StephanPirnbaum commented on migration-guides/1.x-2.0.adoc
> +[options=header]
Can you put all these plugins in the YAML, so that it is easier to copy? The plugin name and url of the repo may be put there as a comment

2023-08-03 06:53 UTC, StephanPirnbaum commented on migration-guides/1.x-2.0.adoc
> +NOTE: Declaring jQAssistant plugins as dependency of the jQAssistant Maven plugin in a `pom.xml` __might__ still work but is no longer supported. Such declarations must be migrated to the `plugins` s
no longer OFFICIALLY supported

2023-08-03 06:53 UTC, StephanPirnbaum commented on migration-guides/1.x-2.0.adoc
> +Plugins are now longer distributed with the command line distribution. Declared plugins (see chapter before) including their required dependencies are resolved and downloaded on startup from Maven re
are NO longer

2023-08-03 06:53 UTC, StephanPirnbaum commented on migration-guides/1.x-2.0.adoc
> +NOTE: It is highly recommended to migrate rules embedded Asciidoc files to XML. The integration with Asciidoc is handled by the https://github.com/jqassistant-tooling/jqassistant-asciidoctorj-extensi
rules embedded IN AsciiDoc. Asciidoc -> AsciiDoc

2023-08-03 06:53 UTC, StephanPirnbaum commented on migration-guides/1.x-2.0.adoc
> +
Hm, I think the description provided here is to short for the typical user. When they used AsciiDoc for documentation before, they want to use it also now. So a complete setup should b provided to keep frustration low. That should be extended to something like the following aspects:
1. Extract Groups, Concepts, and Constraints from AsciiDoc to XML (link 101 where this setup is shown)
2. Setup asciidoctorj for AsciiDoc rendering
3. Explain how jQA macros work in that context

2023-08-11 14:18 UTC, SchniddeMitBrot commented
Ich würde vielleicht noch die Änderung des ddd plugins extra hervorheben (vllt mit einem Link auf das entsprechende Tutorial). Das muss ja nicht nur umplatziert werden. (Vielleicht mit einer Anmerkung, dass das nur für ältere Varianten von jQA relevant ist)

2023-08-11 16:20 UTC, merged